# Generated by Django 6.0.5 on 2026-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_message_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('mention', 'Mention'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('reply', 'Reply'), ('message', 'Message')], max_length=30),
        ),
    ]
