# Generated by Django 6.0.5 on 2026-05-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
