# Generated by Django 6.0.5 on 2026-05-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_localisation'),
        ('accounts', '0003_rename_password_hash_user_password'),
    ]

    operations = [
    ]
