# Generated by Django 6.0.5 on 2026-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260512_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
