# Generated by Django 6.0.5 on 2026-05-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_alter_user_managers_and_more'),
        ('accounts', '0008_add_user_to_localisation'),
    ]

    operations = [
    ]
