# Generated by Django 6.0.5 on 2026-05-14 17:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260514_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/', validators=[accounts.models.validate_image_size]),
        ),
    ]
