# Generated by Django 6.0.5 on 2026-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/banners/'),
        ),
    ]
