# Generated by Django 6.0.5 on 2026-05-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.CharField(max_length=100)),
                ('author_username', models.CharField(max_length=150)),
                ('message_id', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_hash', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
    ]
